<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Weight Maps • zonal</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/readable/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Weight Maps">
<meta property="og:description" content="zonal">
<meta property="og:image" content="/logo.png">
<meta name="robots" content="noindex">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">zonal</a>
        <span class="version label label-danger" data-toggle="tooltip" data-placement="bottom" title="In-development version">0.0.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/01_weight_creation.html">Weight Maps</a>
    </li>
    <li>
      <a href="../articles/02_intersections.html">Zonal Statistics</a>
    </li>
    <li>
      <a href="../articles/03_categorical.html">Categorical Data</a>
    </li>
    <li>
      <a href="../articles/04_nwm_channel.html">NWM Channel Routing Application</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/mikejohnson51/zonal/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="01_weight_creation_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Weight Maps</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/mikejohnson51/zonal/blob/master/vignettes/01_weight_creation.Rmd"><code>vignettes/01_weight_creation.Rmd</code></a></small>
      <div class="hidden name"><code>01_weight_creation.Rmd</code></div>

    </div>

    
    
<div id="methods" class="section level2">
<h2 class="hasAnchor">
<a href="#methods" class="anchor"></a>Methods</h2>
<p>The first step in computing zonal statistics are the need to compute a weight map that can be used to reallocate the gridded data with respect to the percent overlapping each cell. There are two primary packages that tackle this which include <code>intersectr</code> (which uses <code>areal</code> as a back-end) and <code>zonal</code> which uses <code>exactextractr</code>.</p>
<p>From the <code>exactextractr</code> documentation: "_Results from <code>exactextractr</code> are more accurate than other methods because raster pixels that are partially covered by polygons are considered. The significance of partial coverage increases for polygons that are small or irregularly shaped."</p>
<p>The same premise applies to <code>intersectr</code>/<code>areal</code>.</p>
</div>
<div id="so-what-is-a-weight-grid" class="section level2">
<h2 class="hasAnchor">
<a href="#so-what-is-a-weight-grid" class="anchor"></a>So, what is a weight grid?</h2>
<p>A weight grid is unique to the aggregate units and grid its build from. It contains columns documenting the X and Y indexes of each grid cell along with the grid id. The X,Y are relative to the entire grid, while the grid ID is relative to subset within the bounding domain of the aggregations unit(s). Additionally the <code>w</code> stores the percent overlap between the grid cell and the aggregation unit identified by the ID column which is specified in the <code>build</code>weighting_grid` function. An example is shown below:</p>
<div id="option-1-intersectr" class="section level3">
<h3 class="hasAnchor">
<a href="#option-1-intersectr" class="anchor"></a>Option 1: Intersectr:</h3>
<p>Setting up the data for a <code>intersectr</code> weights map requires (1) computing a vector representation of the grid and (2) intersecting this grid with the aggregation units to determine the percent overlap or “coverage fraction”. Below the workflow from the <code>intersectr</code> docs is wrapped in a function that requires a NetCDF file path, a <code>sf</code> geometry set, an ID variable from the geometries, and the variable to extract from the grid.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">intersectr</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/hypertidy/ncmeta">ncmeta</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/mjwoods/RNetCDF">RNetCDF</a></span><span class="op">)</span>

<span class="va">intersectr_weights</span> <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">file</span>, <span class="va">geom</span>, <span class="va">ID</span>, <span class="va">var</span><span class="op">)</span><span class="op">{</span>
  <span class="va">nc_coord_vars</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ncmeta/man/nc_coord_var.html">nc_coord_var</a></span><span class="op">(</span><span class="va">file</span><span class="op">)</span>
  <span class="va">variable_name</span> <span class="op">&lt;-</span> <span class="va">var</span>
  <span class="va">nc_coord_vars</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">nc_coord_vars</span>, <span class="va">variable</span> <span class="op">==</span> <span class="va">variable_name</span><span class="op">)</span>
  
  <span class="va">nc</span>       <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/RNetCDF/man/open.nc.html">open.nc</a></span><span class="op">(</span><span class="va">file</span><span class="op">)</span>
  <span class="va">X_coords</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/RNetCDF/man/var.get.nc.html">var.get.nc</a></span><span class="op">(</span><span class="va">nc</span>, <span class="va">nc_coord_vars</span><span class="op">$</span><span class="va">X</span>, unpack <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
  <span class="va">Y_coords</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/RNetCDF/man/var.get.nc.html">var.get.nc</a></span><span class="op">(</span><span class="va">nc</span>, <span class="va">nc_coord_vars</span><span class="op">$</span><span class="va">Y</span>, unpack <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
  
  <span class="va">nc_prj</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ncmeta/man/nc_gm_to_prj.html">nc_gm_to_prj</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ncmeta/man/nc_grid_mapping_atts.html">nc_grid_mapping_atts</a></span><span class="op">(</span><span class="va">file</span><span class="op">)</span><span class="op">)</span>
    
  <span class="va">cell_geometry</span> <span class="op">=</span> <span class="fu">create_cell_geometry</span><span class="op">(</span>X_coords <span class="op">=</span> <span class="va">X_coords</span>,
                         Y_coords <span class="op">=</span> <span class="va">Y_coords</span>,
                         prj <span class="op">=</span> <span class="va">nc_prj</span>,
                         geom <span class="op">=</span> <span class="va">geom</span>, 
                         buffer_dist <span class="op">=</span> <span class="fl">0.1</span>, <span class="co"># Degrees</span>
                         regularize <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
    
  <span class="va">data_source_cells</span> <span class="op">&lt;-</span> <span class="fu">st_sf</span><span class="op">(</span><span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">cell_geometry</span>, <span class="va">grid_ids</span><span class="op">)</span><span class="op">)</span>
  <span class="va">target_polygons</span>   <span class="op">&lt;-</span> <span class="fu">st_sf</span><span class="op">(</span><span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">geom</span>, <span class="op">!</span><span class="op">!</span><span class="va">ID</span><span class="op">)</span><span class="op">)</span>
  <span class="fu">st_agr</span><span class="op">(</span><span class="va">data_source_cells</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"constant"</span>
  <span class="fu">st_agr</span><span class="op">(</span><span class="va">target_polygons</span><span class="op">)</span>   <span class="op">&lt;-</span> <span class="st">"constant"</span>
    
  <span class="fu">calculate_area_intersection_weights</span><span class="op">(</span>
      <span class="va">data_source_cells</span>,
      <span class="va">target_polygons</span>, allow_lonlat <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="op">}</span></code></pre></div>
</div>
<div id="option-2-zonal" class="section level3">
<h3 class="hasAnchor">
<a href="#option-2-zonal" class="anchor"></a>Option 2: Zonal</h3>
<p>In <code>zonal</code> grid weights are calculated using <code>exactextractr</code> as the back-end. The key function is <code>weighting_grid</code>.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">zonal</span><span class="op">)</span></code></pre></div>
</div>
</div>
<div id="use-cases" class="section level2">
<h2 class="hasAnchor">
<a href="#use-cases" class="anchor"></a>Use Cases</h2>
<p>Here two motivating use cases are shown to compare the efficiency of these approaches. The first covers a large area but has many small aggregation units. The second covers a large area but has a few large polygon aggregation units. Each of these pose a unique set of demands with respect to how the calculation is performed.</p>
</div>
<div id="grid" class="section level2">
<h2 class="hasAnchor">
<a href="#grid" class="anchor"></a>Grid</h2>
<p>The gridded data and aggregate units we are working with can be seen below and downloaded from <a href="https://www.northwestknowledge.net/metdata/data/pet_2020.nc">here</a>:</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">file</span> <span class="op">=</span> <span class="st">'pet_2020.nc'</span>
<span class="op">(</span><span class="va">s</span> <span class="op">=</span> <span class="fu">terra</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/terra/man/rast.html">rast</a></span><span class="op">(</span><span class="va">file</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## dimensions  : 585, 1386, 366  (nrow, ncol, nlyr)
## resolution  : 0.04167, 0.04167  (x, y)
## extent      : -124.8, -67.04, 25.05, 49.42  (xmin, xmax, ymin, ymax)
## coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
## source      : pet_2020.nc 
## varname     : potential_evapotranspiration (pet) 
## names       : poten~43829, poten~43830, poten~43831, poten~43832, poten~43833, poten~43834, ... 
## unit        :          mm,          mm,          mm,          mm,          mm,          mm, ...</code></pre>
<p>Looking at the grid we can see in consists of 810810 grid cells each with a 0.0417 meter by 0.0417 meter resolution. Additionally, there are 366 unique time slices in the NetCDF file.</p>
</div>
<div id="example-01-many-small-aggregation-units" class="section level2">
<h2 class="hasAnchor">
<a href="#example-01-many-small-aggregation-units" class="anchor"></a>Example 01: Many small aggregation units</h2>
<p>Here, we look at an example with ~20,000 watersheds along the east coast.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">geom</span> <span class="op">&lt;-</span> <span class="fu">st_make_valid</span><span class="op">(</span><span class="fu">read_sf</span><span class="op">(</span><span class="st">'hydrofabric.gpkg'</span>, <span class="st">"catchments"</span><span class="op">)</span><span class="op">)</span>

<span class="fu">paint</span><span class="op">(</span><span class="va">geom</span><span class="op">)</span></code></pre></div>
<pre><code>## sf [18041, 4] 
## active geometry column: geom (POLYGON)
## crs: 5070 (NAD83 / Conus Albers)
## crs unit: metre 
## ID        chr cat-1 cat-2 cat-4 cat-5 cat-6 cat-7
## area_sqkm dbl 12.457576 267.083595 8.319214 9.278138 60.577~
## toID      chr nex-2 nex-3 nex-5 nex-6 nex-7 nex-8
## geom      sfc POLY 2,024B POLY 9,064B POLY 1,656B POLY 1,81~</code></pre>
<p>In total we have 18,041 aggregation units to summarize over the 366 time steps.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">bnch</span> <span class="op">&lt;-</span> <span class="fu">bench</span><span class="fu">::</span><span class="fu">mark</span><span class="op">(</span>
  iterations <span class="op">=</span> <span class="fl">1</span>, check <span class="op">=</span> <span class="cn">FALSE</span>, time_unit <span class="op">=</span> <span class="st">"s"</span>,
  intersectr <span class="op">=</span> <span class="fu">intersectr_weights</span><span class="op">(</span><span class="va">file</span>, <span class="va">geom</span>, <span class="st">"ID"</span>, <span class="st">"potential_evapotranspiration"</span><span class="op">)</span>,
  zonal      <span class="op">=</span> <span class="fu"><a href="../reference/weighting_grid.html">weighting_grid</a></span><span class="op">(</span><span class="va">s</span>, <span class="va">geom</span>, <span class="st">"ID"</span><span class="op">)</span>
<span class="op">)</span></code></pre></div>
<p><img src="w-huc01-test-1.png" title="plot of chunk huc01-test" alt="plot of chunk huc01-test" width="100%"></p>
</div>
<div id="example-02-few-large-aggregation-units" class="section level2">
<h2 class="hasAnchor">
<a href="#example-02-few-large-aggregation-units" class="anchor"></a>Example 02: Few, large aggregation units</h2>
<p>Here, we test aggregation the 4km gridded data to 64 counties in Colorado.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">colorado</span>  <span class="op">=</span> <span class="fu">AOI</span><span class="fu">::</span><span class="fu">aoi_get</span><span class="op">(</span>state <span class="op">=</span> <span class="st">"CO"</span>, county <span class="op">=</span> <span class="st">"all"</span><span class="op">)</span>
<span class="fu">paint</span><span class="op">(</span><span class="va">colorado</span><span class="op">)</span></code></pre></div>
<pre><code>## sf [64, 13] 
## active geometry column: geometry (MULTIPOLYGON)
## crs: 4269 (NAD83)
## crs unit: degree 
## statefp           chr 08 08 08 08 08 08
## countyfp          chr 035 095 039 014 037 053
## countyns          chr 00198133 00198163 00198136 01945881 0~
## affgeoid          chr 0500000US08035 0500000US08095 0500000~
## geoid             chr 08035 08095 08039 08014 08037 08053
## name              chr Douglas Phillips Elbert Broomfield Ea~
## lsad              chr 06 06 06 06 06 06
## aland             dbl 2176272717 1781724973 4793658887 8547~
## awater            dbl 6752511 301808 442148 1411781 1884999~
## state_name        chr Colorado Colorado Colorado Colorado C~
## state_abbr        chr CO CO CO CO CO CO
## jurisdiction_type chr state state state state state state
## geometry          sfc MPOLY 872B MPOLY 824B MPOLY 824B MPOL~</code></pre>
<p>In total we have 64 aggregation units to summarize over the 366 time steps.</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">bnch2</span> <span class="op">&lt;-</span> <span class="fu">bench</span><span class="fu">::</span><span class="fu">mark</span><span class="op">(</span>
  iterations <span class="op">=</span> <span class="fl">1</span>, check <span class="op">=</span> <span class="cn">FALSE</span>, time_unit <span class="op">=</span> <span class="st">"s"</span>,
  intersectr <span class="op">=</span> <span class="fu">intersectr_weights</span><span class="op">(</span><span class="va">file</span>, <span class="va">colorado</span>, <span class="st">"name"</span>, <span class="st">"potential_evapotranspiration"</span><span class="op">)</span>,
  zonal      <span class="op">=</span> <span class="fu"><a href="../reference/weighting_grid.html">weighting_grid</a></span><span class="op">(</span><span class="va">file</span>, <span class="va">colorado</span>, <span class="st">"name"</span><span class="op">)</span>
<span class="op">)</span></code></pre></div>
<p><img src="w-colorado-test-1.png" title="plot of chunk colorado-test" alt="plot of chunk colorado-test" width="100%"></p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Mike Johnson.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
