<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />



<title>Weight Maps</title>

<script src="data:application/javascript;base64,Ly8gUGFuZG9jIDIuOSBhZGRzIGF0dHJpYnV0ZXMgb24gYm90aCBoZWFkZXIgYW5kIGRpdi4gV2UgcmVtb3ZlIHRoZSBmb3JtZXIgKHRvCi8vIGJlIGNvbXBhdGlibGUgd2l0aCB0aGUgYmVoYXZpb3Igb2YgUGFuZG9jIDwgMi44KS4KZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignRE9NQ29udGVudExvYWRlZCcsIGZ1bmN0aW9uKGUpIHsKICB2YXIgaHMgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxsKCJkaXYuc2VjdGlvbltjbGFzcyo9J2xldmVsJ10gPiA6Zmlyc3QtY2hpbGQiKTsKICB2YXIgaSwgaCwgYTsKICBmb3IgKGkgPSAwOyBpIDwgaHMubGVuZ3RoOyBpKyspIHsKICAgIGggPSBoc1tpXTsKICAgIGlmICghL15oWzEtNl0kL2kudGVzdChoLnRhZ05hbWUpKSBjb250aW51ZTsgIC8vIGl0IHNob3VsZCBiZSBhIGhlYWRlciBoMS1oNgogICAgYSA9IGguYXR0cmlidXRlczsKICAgIHdoaWxlIChhLmxlbmd0aCA+IDApIGgucmVtb3ZlQXR0cmlidXRlKGFbMF0ubmFtZSk7CiAgfQp9KTsK"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="data:text/css,body%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Amargin%3A%201em%20auto%3B%0Amax%2Dwidth%3A%20700px%3B%0Aoverflow%3A%20visible%3B%0Apadding%2Dleft%3A%202em%3B%0Apadding%2Dright%3A%202em%3B%0Afont%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0Afont%2Dsize%3A%2014px%3B%0Aline%2Dheight%3A%201%2E35%3B%0A%7D%0A%23TOC%20%7B%0Aclear%3A%20both%3B%0Amargin%3A%200%200%2010px%2010px%3B%0Apadding%3A%204px%3B%0Awidth%3A%20400px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Aborder%2Dradius%3A%205px%3B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Afont%2Dsize%3A%2013px%3B%0Aline%2Dheight%3A%201%2E3%3B%0A%7D%0A%23TOC%20%2Etoctitle%20%7B%0Afont%2Dweight%3A%20bold%3B%0Afont%2Dsize%3A%2015px%3B%0Amargin%2Dleft%3A%205px%3B%0A%7D%0A%23TOC%20ul%20%7B%0Apadding%2Dleft%3A%2040px%3B%0Amargin%2Dleft%3A%20%2D1%2E5em%3B%0Amargin%2Dtop%3A%205px%3B%0Amargin%2Dbottom%3A%205px%3B%0A%7D%0A%23TOC%20ul%20ul%20%7B%0Amargin%2Dleft%3A%20%2D2em%3B%0A%7D%0A%23TOC%20li%20%7B%0Aline%2Dheight%3A%2016px%3B%0A%7D%0Atable%20%7B%0Amargin%3A%201em%20auto%3B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dcolor%3A%20%23DDDDDD%3B%0Aborder%2Dstyle%3A%20outset%3B%0Aborder%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0Aborder%2Dwidth%3A%202px%3B%0Apadding%3A%205px%3B%0Aborder%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dstyle%3A%20inset%3B%0Aline%2Dheight%3A%2018px%3B%0Apadding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0Aborder%2Dleft%2Dstyle%3A%20none%3B%0Aborder%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Ap%20%7B%0Amargin%3A%200%2E5em%200%3B%0A%7D%0Ablockquote%20%7B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Apadding%3A%200%2E25em%200%2E75em%3B%0A%7D%0Ahr%20%7B%0Aborder%2Dstyle%3A%20solid%3B%0Aborder%3A%20none%3B%0Aborder%2Dtop%3A%201px%20solid%20%23777%3B%0Amargin%3A%2028px%200%3B%0A%7D%0Adl%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Adl%20dd%20%7B%0Amargin%2Dbottom%3A%2013px%3B%0Amargin%2Dleft%3A%2013px%3B%0A%7D%0Adl%20dt%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Aul%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Aul%20li%20%7B%0Alist%2Dstyle%3A%20circle%20outside%3B%0A%7D%0Aul%20ul%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Apre%2C%20code%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0Acolor%3A%20%23333%3B%0Awhite%2Dspace%3A%20pre%2Dwrap%3B%20%0A%7D%0Apre%20%7B%0Aborder%2Dradius%3A%203px%3B%0Amargin%3A%205px%200px%2010px%200px%3B%0Apadding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0Afont%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0Apadding%3A%202px%200px%3B%0A%7D%0Adiv%2Efigure%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0Abackground%2Dcolor%3A%20%23FFFFFF%3B%0Apadding%3A%202px%3B%0Aborder%3A%201px%20solid%20%23DDDDDD%3B%0Aborder%2Dradius%3A%203px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Amargin%3A%200%205px%3B%0A%7D%0Ah1%20%7B%0Amargin%2Dtop%3A%200%3B%0Afont%2Dsize%3A%2035px%3B%0Aline%2Dheight%3A%2040px%3B%0A%7D%0Ah2%20%7B%0Aborder%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Apadding%2Dbottom%3A%202px%3B%0Afont%2Dsize%3A%20145%25%3B%0A%7D%0Ah3%20%7B%0Aborder%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Afont%2Dsize%3A%20120%25%3B%0A%7D%0Ah4%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0Amargin%2Dleft%3A%208px%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Ah5%2C%20h6%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23ccc%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%230033dd%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%20%7B%0Acolor%3A%20%236666ff%3B%20%7D%0Aa%3Avisited%20%7B%0Acolor%3A%20%23800080%3B%20%7D%0Aa%3Avisited%3Ahover%20%7B%0Acolor%3A%20%23BB00BB%3B%20%7D%0Aa%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0Aa%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%0A" type="text/css" />




</head>

<body>




<h1 class="title toc-ignore">Weight Maps</h1>



<div id="methods" class="section level2">
<h2>Methods</h2>
<p>The first step in computing zonal statistics are the need to compute a weight map that can be used to reallocate the gridded data with respect to the percent overlapping each cell. There are two primary packages that tackle this which include <code>intersectr</code> (which uses <code>areal</code> as a back-end) and <code>zonal</code> which uses <code>exactextractr</code>.</p>
<div id="option-1-intersectr" class="section level3">
<h3>Option 1: Intersectr:</h3>
<p>Setting up the data for a <code>intersectr</code> weights map requires (1) computing a vector representation of the grid and (2) intersecting this grid with the aggregation units to determine the percent overlap or “coverage fraction”. Below the workflow from the <code>intersectr</code> docs is wrapped in a function that requires a NetCDF file path, a <code>sf</code> geometry set, an ID variable from the geometries, and the variable to extract from the grid.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(intersectr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ncmeta)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RNetCDF)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>intersectr_weights <span class="ot">=</span> <span class="cf">function</span>(file, geom, ID, var){</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  nc_coord_vars <span class="ot">&lt;-</span> <span class="fu">nc_coord_var</span>(file)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  variable_name <span class="ot">&lt;-</span> var</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  nc_coord_vars <span class="ot">&lt;-</span> <span class="fu">filter</span>(nc_coord_vars, variable <span class="sc">==</span> variable_name)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  nc       <span class="ot">&lt;-</span> <span class="fu">open.nc</span>(file)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  X_coords <span class="ot">&lt;-</span> <span class="fu">var.get.nc</span>(nc, nc_coord_vars<span class="sc">$</span>X, <span class="at">unpack =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  Y_coords <span class="ot">&lt;-</span> <span class="fu">var.get.nc</span>(nc, nc_coord_vars<span class="sc">$</span>Y, <span class="at">unpack =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  nc_prj <span class="ot">&lt;-</span> <span class="fu">nc_gm_to_prj</span>(<span class="fu">nc_grid_mapping_atts</span>(file))</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  cell_geometry <span class="ot">=</span> <span class="fu">create_cell_geometry</span>(<span class="at">X_coords =</span> X_coords,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Y_coords =</span> Y_coords,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>                         <span class="at">prj =</span> nc_prj,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>                         <span class="at">geom =</span> geom, </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>                         <span class="at">buffer_dist =</span> <span class="fl">0.1</span>, <span class="co"># Degrees</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>                         <span class="at">regularize =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  data_source_cells <span class="ot">&lt;-</span> <span class="fu">st_sf</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(cell_geometry, grid_ids))</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  target_polygons   <span class="ot">&lt;-</span> <span class="fu">st_sf</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(geom, <span class="sc">!!</span>ID))</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_agr</span>(data_source_cells) <span class="ot">&lt;-</span> <span class="st">&quot;constant&quot;</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_agr</span>(target_polygons)   <span class="ot">&lt;-</span> <span class="st">&quot;constant&quot;</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate_area_intersection_weights</span>(</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>      data_source_cells,</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>      target_polygons, <span class="at">allow_lonlat =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
</div>
<div id="option-2-zonal" class="section level3">
<h3>Option 2: Zonal</h3>
<p>In <code>zonal</code> grid weights are calculated using <code>exactextractr</code> as the back-end. The key function needed is <code>weighting_grid</code>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(zonal)</span></code></pre></div>
</div>
</div>
<div id="use-cases" class="section level2">
<h2>Use Cases</h2>
<p>Here two motivating use cases are shown to compare the efficiency of these two approaches. The first covers a large area but has many small aggregation units. The second also covers a large area but has a few large polygon aggregation units. Each of these poses a unique set of demands with respect to how the calculation is performed.</p>
</div>
<div id="grid" class="section level2">
<h2>Grid</h2>
<p>The gridded data and aggregate units we are working with can be seen below:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>file <span class="ot">=</span> <span class="st">&#39;/Users/mjohnson/Downloads/pet_1979.nc&#39;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>(<span class="at">s =</span> terra<span class="sc">::</span><span class="fu">rast</span>(file))</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## dimensions  : 585, 1386, 365  (nrow, ncol, nlyr)
## resolution  : 0.04166667, 0.04166667  (x, y)
## extent      : -124.7875, -67.0375, 25.04583, 49.42083  (xmin, xmax, ymin, ymax)
## coord. ref. : +proj=longlat +datum=WGS84 +no_defs 
## source      : pet_1979.nc 
## varname     : potential_evapotranspiration (pet) 
## names       : poten~28854, poten~28855, poten~28856, poten~28857, poten~28858, poten~28859, ... 
## unit        :          mm,          mm,          mm,          mm,          mm,          mm, ...</code></pre>
<p>Looking at the grid we can see in consists of 8.1081^{5} grid cells each with a 0.0416667 meter by 0.0416667 meter resolution. Additionally, there are 365 unique time slices in the NetCDF file.</p>
<div id="example-01-many-small-aggregation-units" class="section level3">
<h3>Example 01: Many small aggregation units</h3>
<p>Here, we look at an example with ~20,000 watersheds along the east coast.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>geom <span class="ot">&lt;-</span> <span class="fu">st_make_valid</span>(<span class="fu">read_sf</span>(<span class="st">&#39;/Users/mjohnson/github/hydrofabric/workflow/nhd_workflows/cache/ngen_01a-4.gpkg&#39;</span>, <span class="st">&quot;catchments&quot;</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(geom)</span></code></pre></div>
<pre><code>## Rows: 19,700
## Columns: 3
## $ comid    &lt;dbl&gt; 4289595, 4290057, 4287059, 4287061, 4292649, 4292651, 4287199…
## $ areasqkm &lt;dbl&gt; 12.2707416, 4.0614450, 2.8056073, 6.7866652, 18.1573074, 27.8…
## $ geom     &lt;MULTIPOLYGON [m]&gt; MULTIPOLYGON (((1976295 290..., MULTIPOLYGON (((…</code></pre>
<p>In total we have 19,700 aggregation units to summarize over the 365 time steps.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>bnch <span class="ot">&lt;-</span> bench<span class="sc">::</span><span class="fu">mark</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">iterations =</span> <span class="dv">1</span>, <span class="at">check =</span> <span class="cn">FALSE</span>, <span class="at">time_unit =</span> <span class="st">&quot;s&quot;</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">intersectr =</span> <span class="fu">intersectr_weights</span>(file, geom, <span class="st">&quot;comid&quot;</span>, <span class="st">&quot;potential_evapotranspiration&quot;</span>),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">zonal      =</span> <span class="fu">weighting_grid</span>(s, geom, <span class="st">&quot;comid&quot;</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:right;">
expression
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:right;">
mem_alloc
</th>
<th style="text-align:right;">
median_rel
</th>
<th style="text-align:right;">
mem_rel
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
intersectr
</td>
<td style="text-align:right;">
45.86202
</td>
<td style="text-align:right;">
873.612236MB
</td>
<td style="text-align:right;">
1.967527
</td>
<td style="text-align:right;">
1.000000
</td>
</tr>
<tr>
<td style="text-align:right;">
zonal
</td>
<td style="text-align:right;">
23.30947
</td>
<td style="text-align:right;">
1.066093GB
</td>
<td style="text-align:right;">
1.000000
</td>
<td style="text-align:right;">
1.249616
</td>
</tr>
</tbody>
</table>
</div>
<div id="exxample-02-few-large-aggregation-units" class="section level3">
<h3>Exxample 02: Few, large aggregation units</h3>
<p>Here, we test aggregation the 4km gridded data to 64 counties in Colorado.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>colorado  <span class="ot">=</span> AOI<span class="sc">::</span><span class="fu">aoi_get</span>(<span class="at">state =</span> <span class="st">&quot;CO&quot;</span>, <span class="at">county =</span> <span class="st">&quot;all&quot;</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(colorado)</span></code></pre></div>
<pre><code>## Rows: 64
## Columns: 13
## $ statefp           &lt;chr&gt; &quot;08&quot;, &quot;08&quot;, &quot;08&quot;, &quot;08&quot;, &quot;08&quot;, &quot;08&quot;, &quot;08&quot;, &quot;08&quot;, &quot;08&quot;…
## $ countyfp          &lt;chr&gt; &quot;035&quot;, &quot;095&quot;, &quot;039&quot;, &quot;014&quot;, &quot;037&quot;, &quot;053&quot;, &quot;025&quot;, &quot;00…
## $ countyns          &lt;chr&gt; &quot;00198133&quot;, &quot;00198163&quot;, &quot;00198136&quot;, &quot;01945881&quot;, &quot;001…
## $ affgeoid          &lt;chr&gt; &quot;0500000US08035&quot;, &quot;0500000US08095&quot;, &quot;0500000US08039&quot;…
## $ geoid             &lt;chr&gt; &quot;08035&quot;, &quot;08095&quot;, &quot;08039&quot;, &quot;08014&quot;, &quot;08037&quot;, &quot;08053&quot;…
## $ name              &lt;chr&gt; &quot;Douglas&quot;, &quot;Phillips&quot;, &quot;Elbert&quot;, &quot;Broomfield&quot;, &quot;Eagl…
## $ lsad              &lt;chr&gt; &quot;06&quot;, &quot;06&quot;, &quot;06&quot;, &quot;06&quot;, &quot;06&quot;, &quot;06&quot;, &quot;06&quot;, &quot;06&quot;, &quot;06&quot;…
## $ aland             &lt;dbl&gt; 2176272717, 1781724973, 4793658887, 85478497, 436287…
## $ awater            &lt;dbl&gt; 6752511, 301808, 442148, 1411781, 18849997, 15324686…
## $ state_name        &lt;chr&gt; &quot;Colorado&quot;, &quot;Colorado&quot;, &quot;Colorado&quot;, &quot;Colorado&quot;, &quot;Col…
## $ state_abbr        &lt;chr&gt; &quot;CO&quot;, &quot;CO&quot;, &quot;CO&quot;, &quot;CO&quot;, &quot;CO&quot;, &quot;CO&quot;, &quot;CO&quot;, &quot;CO&quot;, &quot;CO&quot;…
## $ jurisdiction_type &lt;chr&gt; &quot;state&quot;, &quot;state&quot;, &quot;state&quot;, &quot;state&quot;, &quot;state&quot;, &quot;state&quot;…
## $ geometry          &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-105.2178 3..., MULTIPO…</code></pre>
<p>In total we have 64 aggregation units to summarize over the 365 time steps.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>bnch2 <span class="ot">&lt;-</span> bench<span class="sc">::</span><span class="fu">mark</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">iterations =</span> <span class="dv">1</span>, <span class="at">check =</span> <span class="cn">FALSE</span>, <span class="at">time_unit =</span> <span class="st">&quot;s&quot;</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">intersectr =</span> <span class="fu">intersectr_weights</span>(file, colorado, <span class="st">&quot;name&quot;</span>, <span class="st">&quot;potential_evapotranspiration&quot;</span>),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">zonal      =</span> <span class="fu">weighting_grid</span>(file, colorado, <span class="st">&quot;name&quot;</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:right;">
expression
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:right;">
mem_alloc
</th>
<th style="text-align:right;">
median_rel
</th>
<th style="text-align:right;">
mem_rel
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
intersectr
</td>
<td style="text-align:right;">
67.7004451
</td>
<td style="text-align:right;">
961.65184MB
</td>
<td style="text-align:right;">
233.6811
</td>
<td style="text-align:right;">
17.82503
</td>
</tr>
<tr>
<td style="text-align:right;">
zonal
</td>
<td style="text-align:right;">
0.2897129
</td>
<td style="text-align:right;">
53.94952MB
</td>
<td style="text-align:right;">
1.0000
</td>
<td style="text-align:right;">
1.00000
</td>
</tr>
</tbody>
</table>
<p>Notably the <code>intersectr</code> approach, based on vector intersections, is unable to scale well when the aggregation units are large.</p>
</div>
</div>
<div id="so-what-is-a-weight-grid" class="section level2">
<h2>So, what is a weight grid?</h2>
<p>A weight grid is unique to the aggregate units and grid its build from. It contains columns documenting the X and Y indexes of each grid cell along with the grid id. The X,Y are realtive to the entire grid, while the grid ID is relative to subsetwithin the bounding domain of the aggregations unit(s). Additionally the <code>w</code> stores the percent overlap between the grid cell and the aggregation unit identified by the ID column which is speified in the <code>build</code>weighting_grid` function. An example is shown below:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>zonal      <span class="ot">=</span> zonal<span class="sc">::</span><span class="fu">weighting_grid</span>(file, colorado, <span class="st">&quot;name&quot;</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(zonal)</span></code></pre></div>
<pre><code>##      Y   X grid_id         w   name
## 1: 203 378     173 0.2724911 Moffat
## 2: 203 379     174 0.9152694 Moffat
## 3: 203 380     175 0.9145876 Moffat
## 4: 203 381     176 0.9139059 Moffat
## 5: 203 382     177 0.9132242 Moffat
## 6: 203 383     178 0.9125424 Moffat</code></pre>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
